### ISSUE TITLE
check_n_format don't take input file argument into account

### ISSUE THREAD

**Issue by FinLouarn** [zhengying-liu/autodl-contrib#1]
What ever the input file given as an argument in the command line it always use the default value, hard coded as tf.flags :
`tf.flags.DEFINE_string('raw_dataset_dir', 'file_format/mini-cifar',
                       "Path to raw dataset.")`

because in the "__main__" it's not reading input_dir from sys.args but from FLAGS only:

`input_dir = FLAGS.raw_dataset_dir`

**Comment by Didayolo** [comment]
`tf.flags` can be passed as command line argument like this:

`python3 check_n_format.py -raw_dataset_dir=file_format/another_dataset`

It is not hard coded but a default value.

However I don't really support this way of calling arguments because it is heavier and not retro-compatible. We will check this out soon. Thank you for your feedback.

**Comment by Didayolo** [comment]
The command line is now as before:

`python3 check_n_format.py file_format/another_dataset`
